[package]
name = "rune-io"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
rfd = "0.15.0"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
