[package]
name = "rune-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
wasmtime = { version = "19", default-features = true }
serde_json = "1.0"
tracing = "0.1"
rune-ir = { path = "../rune-ir" }
thiserror = "1.0"
wat = "1.0"

[dev-dependencies]
